[tools]
uv = "latest"
pre-commit = "latest"

[env]
DB_PATH = "{{config_root}}/data/events.db"

[shell_alias]
start = "uv run uvicorn webhook_receiver.app:create_app --factory --host 0.0.0.0 --port 8000"
locust = "uv run locust -f load_tests/locustfile.py --host http://localhost:8000"
locust_headless = "uv run locust -f load_tests/locustfile.py --headless -u 50 -r 10 --run-time 60s --host http://localhost:8000"
locust_1000 = "uv run locust -f load_tests/locustfile_requirements.py --host http://localhost:8000"
locust_1000_headless = "uv run locust -f load_tests/locustfile_requirements.py --headless --run-time 90s --host http://localhost:8000"
locust_final = "uv run locust -f load_tests/locustfile_final.py --headless --run-time 90s --host http://localhost:8000"
locust_final_interactive = "uv run locust -f load_tests/locustfile_final.py --host http://localhost:8000"
